name: Java CI (1.19.2 Fabric)

on:
  workflow_dispatch:
    branches:
      - 1.19/fabric
    inputs:
      release_type:
        description: 'Release Type'
        required: true
        type: choice
        default: 'release'
        options:
          - 'release'
          - 'beta'
          - 'alpha'
          - 'none'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 30

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build and Publish with Gradle
        uses: gradle/gradle-build-action@v2
        env:
          FTB_MAVEN_TOKEN: ${{ secrets.FTB_MAVEN_TOKEN }}
          SAPS_TOKEN: ${{ secrets.SAPS_TOKEN }}
        with:
          arguments: build publish --stacktrace --no-daemon

      - name: Release to CurseForge
        uses: gradle/gradle-build-action@v2
        if: ${{ inputs.release_type != 'none' }}
        env:
          GIT_COMMIT: ${{ github.event.after }}
          GIT_PREVIOUS_COMMIT: ${{ github.event.before }}
          CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
          RELEASE_TYPE: ${{ inputs.release_type }}
        with:
          arguments: curseforge --stacktrace --no-daemon